#!/usr/bin/env python
# coding=utf-8
import os
import sys


def ssh_login_without_password_setup(server_name):
    localPath = '~/.ssh'
    localPath = os.path.expanduser(localPath)
    if not os.path.isdir(localPath):
        cmd = 'ssh-keygen -t rsa'
        os.system(cmd)

    cmd = 'ssh {0} mkdir -p ssh'.format(server_name)
    os.system(cmd)

    cmd = 'cat {0}/id_rsa.pub | ssh {1} "cat >> ~/.ssh/authorized_keys"'.format(localPath, server_name)
    os.system(cmd)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("usage: {0} userName@serverName".format(sys.argv[0]))
    else:
        server = sys.argv[1]
        ssh_login_without_password_setup(server)
