#!/usr/bin/env python
# coding=utf-8
import os
import sys

def sshSetup(server):
    localPath = '~/.ssh';
    localPath = os.path.expanduser(localPath);
    if os.path.isdir(localPath) == False:
        cmd = 'ssh-keygen -t rsa';
        os.system(cmd);

    cmd = 'ssh %s mkdir -p .ssh' % server;
    os.system(cmd);

    cmd = 'cat %s/id_rsa.pub | ssh %s "cat >> .ssh/authorized_keys"' %(localPath, server);
    os.system(cmd);

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("usage: %s userName@serverName" % sys.argv[0]);
    else: 
        server = sys.argv[1];
        sshSetup(server);




